# Generated by Django 2.2.1 on 2019-09-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_name', models.CharField(max_length=200)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Classrooms')),
            ],
        ),
    ]
