# Generated by Django 2.2.1 on 2019-09-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=200)),
                ('student', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homework_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.CharField(max_length=200)),
                ('student', models.CharField(max_length=200)),
            ],
        ),
    ]
